version: '3'
services:
  frontend:
    build: frontend/
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - backend 
    volumes:
      - ./frontend/src:/frontend/src   
  backend:
    build: backend/
    container_name: BotApi
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Secure123'
      MYSQL_HOST: database
      MYSQL_PORT: 3307
    depends_on:
      - database
  database:
    image: mysql:8.0.29
    container_name: BotDatabase
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 'Secure123'
      MYSQL_DATABASE: BotTelegram
    ports:
      - "3307:3307"

